<a href="https://colab.research.google.com/github/gangasani-anusha/DeepLearning_Assignment2/blob/main/Tensor_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a = [1.0, 2.0, 1.0]
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [2]:
import torch 
a = torch.ones(6) 
a

tensor([1., 1., 1., 1., 1., 1.])

In [3]:
#convert into float
float(a[1])

1.0

In [4]:

#assign new value to index 2
a[2] = 8.0
a

tensor([1., 1., 8., 1., 1., 1.])

In [5]:
points = torch.zeros(6) 
points[0] = 4.0 
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [6]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [7]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [8]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [9]:
points.shape

torch.Size([3, 2])

In [10]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [11]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points[0, 1]

tensor(1.)

In [13]:
points[0]

tensor([4., 1.])

### Storage Method

In [14]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [15]:
points_storage = points.storage()
points_storage[0]

4.0

In [16]:
points.storage()[1]

1.0

In [17]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [18]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [19]:
second_point.size()

torch.Size([2])

In [20]:
second_point.shape

torch.Size([2])

In [21]:
points.stride()

(2, 1)

In [22]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [23]:
second_point.storage_offset()

2

In [24]:
second_point.stride()

(1,)

In [25]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [26]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [27]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [28]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [29]:
id(points.storage()) == id(points_t.storage())

True

In [30]:
points.stride()
points_t.stride()

(1, 2)

### Operations

In [31]:
tensor = torch.rand(3, 4)


if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [32]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [33]:
x = torch.cat([tensor, tensor, tensor], dim=1)
print(x)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### Transpose

In [34]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [35]:
transpose_t.shape

torch.Size([5, 4, 3])

In [36]:
some_t.stride()
transpose_t.stride()

(1, 5, 20)

In [37]:
points.is_contiguous()
points_t.is_contiguous()

False

In [38]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [39]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [40]:
points_t.stride()

(1, 2)

In [41]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [42]:
points_t_cont.stride()

(3, 1)

In [43]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

In [44]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
short_points.dtype

torch.int16

In [45]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [46]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [47]:
points_64 = torch.rand(5, dtype=torch.double)  
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [48]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
some_list = list(range(6))
some_list[:]     
some_list[1:4]   
some_list[1:]    
some_list[:4]    
some_list[:-1]   
some_list[1:4:2] 

[1, 3]

In [49]:
points[1:]       
points[1:, :]    
points[1:, 0]    
points[None]     

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [50]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [51]:
points = torch.from_numpy(points_np)

### Normalize Tensor

In [52]:
# Input tensor
counts = [[0, 1, 0, 0],
          [0, 1, 1, 0],
          [1, 1, 1, 1]]

In [53]:
import tensorflow as tf
tf.cast(tf.divide(counts, tf.expand_dims(tf.reduce_sum(counts, axis=1), axis=1)), tf.float32)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.5 , 0.5 , 0.  ],
       [0.25, 0.25, 0.25, 0.25]], dtype=float32)>

### Element-wise

In [54]:
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [55]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [56]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [57]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
