<a href="https://colab.research.google.com/github/gangasani-anusha/DeepLearning_Assignment2/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
#scalar tensor
scalar_rank = tf.constant(10)
print(scalar_rank)

tf.Tensor(10, shape=(), dtype=int32)


In [5]:
#vector tensor
vector_rank = tf.constant([6.0, 9.0, 3.0])
print(vector_rank)

tf.Tensor([6. 9. 3.], shape=(3,), dtype=float32)


In [7]:
#matrix1 tensor
matrix1_rank = tf.constant([[3, 7],
                             [5, 8],
                             [6, 2]], dtype=tf.float16)
print(matrix1_rank)

tf.Tensor(
[[3. 7.]
 [5. 8.]
 [6. 2.]], shape=(3, 2), dtype=float16)


In [8]:
#matrix2 tensor
matrix2_rank = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(matrix2_rank)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [10]:
np.array(matrix1_rank)

array([[3., 7.],
       [5., 8.],
       [6., 2.]], dtype=float16)

In [11]:
matrix1_rank.numpy()

array([[3., 7.],
       [5., 8.],
       [6., 2.]], dtype=float16)

### Math Operations

In [17]:
x = tf.constant([[3, 7],
                 [5, 4]])
y = tf.constant([[6, 1],
                 [3, 4]]) 

print(tf.add(x, y), "\n")
print(tf.multiply(x, y), "\n")
print(tf.matmul(x, y), "\n")

tf.Tensor(
[[9 8]
 [8 8]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[18  7]
 [15 16]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[39 31]
 [42 21]], shape=(2, 2), dtype=int32) 



In [18]:
print(x + y, "\n") 
print(x * y, "\n") 
print(x @ y, "\n") 

tf.Tensor(
[[9 8]
 [8 8]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[18  7]
 [15 16]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[39 31]
 [42 21]], shape=(2, 2), dtype=int32) 



In [19]:
z = tf.constant([[3.5, 2.0], [10.0, 4.0]])

# Find the largest value
print(tf.reduce_max(z))
# Find the index of the largest value
print(tf.argmax(z))
# Compute the softmax
print(tf.nn.softmax(z))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 1], shape=(2,), dtype=int64)
tf.Tensor(
[[0.81757444 0.18242551]
 [0.9975274  0.00247262]], shape=(2, 2), dtype=float32)


### Shape of Tensors

In [21]:
matrix1D = tf.zeros([3, 2, 4, 5])
print("Type of every element:", matrix1D.dtype)
print("Number of axes:", matrix1D.ndim)
print("Shape of tensor:", matrix1D.shape)
print("Elements along axis 0 of tensor:", matrix1D.shape[0])
print("Elements along the last axis of tensor:", matrix1D.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(matrix1D).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


### Indexing

In [23]:
a = tf.constant([7,8,9,3,45,23,12,6,4])
print(a.numpy())

[ 7  8  9  3 45 23 12  6  4]


In [24]:
print("First:", a[0].numpy())
print("Second:", a[1].numpy())
print("Last:", a[-1].numpy())

First: 7
Second: 8
Last: 4


In [25]:
#indexing with a : in slices
print("Everything:", a[:].numpy())
print("Before 4:", a[:4].numpy())
print("From 4 to the end:", a[4:].numpy())
print("From 2, before 7:", a[2:7].numpy())
print("Every other item:", a[::2].numpy())
print("Reversed:", a[::-1].numpy())

Everything: [ 7  8  9  3 45 23 12  6  4]
Before 4: [7 8 9 3]
From 4 to the end: [45 23 12  6  4]
From 2, before 7: [ 9  3 45 23 12]
Every other item: [ 7  9 45 12  4]
Reversed: [ 4  6 12 23 45  3  9  8  7]


In [34]:
matrix1_rank.numpy()
matrix1_rank[1, 1].numpy()



# Get row and column tensors
print("Second row:", matrix1_rank[1, :].numpy())
print("Second column:", matrix1_rank[:, 1].numpy())
print("Last row:", matrix1_rank[-1, :].numpy())
print("First item in last column:", matrix1_rank[0, -1].numpy())
print("Skip the first row:")
print(matrix1_rank[1:, :].numpy(), "\n")


Second row: [5. 8.]
Second column: [7. 8. 2.]
Last row: [6. 2.]
First item in last column: 7.0
Skip the first row:
[[5. 8.]
 [6. 2.]] 



In [35]:
#3 axes tensor indexing
print(matrix2_rank[:, :, 4])

tf.Tensor(
[[ 4  9]
 [14 19]
 [24 29]], shape=(3, 2), dtype=int32)


### TypeCasting with Tensors

In [39]:
u = tf.constant([6.1, 2.4, 5.3], dtype=tf.float64)
v = tf.cast(u, dtype=tf.float16)

s = tf.cast(v, dtype=tf.uint8)
print(s)

tf.Tensor([6 2 5], shape=(3,), dtype=uint8)


### Conversions

In [42]:
arr = np.ones([3, 3])

print("convert numpy arrays to Tensors automatically")
tensor = tf.multiply(arr, 42)
print(tensor)

print("And NumPy operations")
print(np.add(tensor, 1))

print("The .numpy() method explicitly converts")
print(tensor.numpy())

convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And NumPy operations
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [43]:
k = tf.random.uniform([3, 3])

print("GPU"),
print(tf.config.list_physical_devices("GPU"))

print("Tensor on GPU #0:  "),
print(k.device.endswith('GPU:0'))

GPU
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Tensor on GPU #0:  
True


In [45]:
import time
def time_matmul(k):
  start = time.time()
  for loop in range(10):
    tf.matmul(k, k)

  result = time.time()-start

  print("10 loops: {:0.2f}ms".format(1000*result))

# Brute execution
print("On CPU:")
with tf.device("CPU:0"):
  k = tf.random.uniform([1000, 1000])
  assert k.device.endswith("CPU:0")
  time_matmul(k)

# Brute execution
if tf.config.list_physical_devices("GPU"):
  print("On GPU:")
  with tf.device("GPU:0"):
    k = tf.random.uniform([1000, 1000])
    assert k.device.endswith("GPU:0")
    time_matmul(k)

On CPU:
10 loops: 632.44ms
On GPU:
10 loops: 1440.68ms


### Creating Source Dataset

In [46]:
tes = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])
import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
  f.write("""Line 1
Line 2
Line 3
  """)

ds_file = tf.data.TextLineDataset(filename)

In [47]:
tes = tes.map(tf.square).shuffle(2).batch(2)

ds_file = ds_file.batch(2)

In [48]:
print('Elements of tes:')
for k in tes:
  print(k)

print('\nElements in ds_file:')
for k in ds_file:
  print(k)

Elements of tes:
tf.Tensor([1 9], shape=(2,), dtype=int32)
tf.Tensor([16  4], shape=(2,), dtype=int32)
tf.Tensor([25 36], shape=(2,), dtype=int32)

Elements in ds_file:
tf.Tensor([b'Line 1' b'Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'Line 3' b'  '], shape=(2,), dtype=string)


### Broadcasting

In [49]:
x = tf.constant([1, 2, 3])

y = tf.constant(2)
z = tf.constant([2, 2, 2])
# All of these are the same computation
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [ ]:
x = tf.reshape(x,[3,1])
y = tf.range(1, 5)
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

In [51]:
print(tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


### Sparse Tensors

In [52]:
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


### Ragged Tensors

In [54]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


In [55]:
print(ragged_tensor.shape)

(4, None)


### String Tensors

In [56]:
#scalar string tensor
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)

tf.Tensor(b'Gray wolf', shape=(), dtype=string)


In [57]:
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])

print(tensor_of_strings)

tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)


In [58]:
#split a string into a set of tensors
print(tf.strings.split(scalar_string_tensor, sep=" "))

tf.Tensor([b'Gray' b'wolf'], shape=(2,), dtype=string)


In [59]:
print(tf.strings.split(tensor_of_strings))

<tf.RaggedTensor [[b'Gray', b'wolf'], [b'Quick', b'brown', b'fox'], [b'Lazy', b'dog']]>


In [60]:
#convert string to number
text = tf.constant("1 10 100")
print(tf.strings.to_number(tf.strings.split(text, " ")))

tf.Tensor([  1.  10. 100.], shape=(3,), dtype=float32)


In [61]:
#type casting string tensors
byte_strings = tf.strings.bytes_split(tf.constant("Duck"))
byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8)
print("Byte strings:", byte_strings)
print("Bytes:", byte_ints)

Byte strings: tf.Tensor([b'D' b'u' b'c' b'k'], shape=(4,), dtype=string)
Bytes: tf.Tensor([ 68 117  99 107], shape=(4,), dtype=uint8)
